services:
  dash:
    build: .
    container_name: dashapp
    ports:
      - "8050:8050"
    volumes:
      - ./dash_data:/dash_data
      - ./assets:/app/assets
    environment:
      DASH_DEBUG: "1"
    restart: unless-stopped